In [1]:
import numpy as np

In [2]:
a = np.arange(25)
a = a.reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [3]:
a[2, 2]

12

In [4]:
def q_table(rows):
    # Each state can have 4 actions, Up, Right, Down & Left
    q = np.random.randn(rows * rows, 4)
    return q

In [5]:
q_table(5)

array([[-0.80928001, -0.60553794,  0.45308976,  0.43613244],
       [-0.66224389,  0.06628663,  0.58126594,  0.04151032],
       [ 0.94342997,  0.4254658 , -0.48410518,  0.90997783],
       [ 1.54863088,  0.86278822, -0.39179345,  0.42953196],
       [ 0.75080831, -0.5968918 , -1.01618132,  0.44171301],
       [ 1.92467193, -1.37112191, -0.06883911,  0.60906969],
       [-0.07843494, -1.39994086, -0.44358361,  0.36842005],
       [-0.1510805 ,  0.73365946,  0.57219791, -0.8768487 ],
       [ 1.16728614, -0.23819003,  0.1074089 ,  0.33953936],
       [-0.56565144, -0.7227623 , -0.56523955, -1.02507639],
       [-1.1307588 ,  0.80405059, -1.07848214, -0.59267133],
       [ 0.91089019, -1.76507121, -1.97581349, -2.020169  ],
       [-0.58550136, -0.47355679, -0.40237398,  0.24111951],
       [-0.54911552, -1.7584141 ,  0.39710198, -1.91083847],
       [ 1.16819426, -0.83956332, -0.4151713 ,  0.37285525],
       [-2.69543232, -1.25297192,  0.92861395, -0.62062233],
       [ 1.25425654, -2.

In [6]:
def lookup_table(rows):
    table = np.arange(rows * rows).reshape(rows, -1)
    return table

In [7]:
table = lookup_table(5)
table

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [8]:
table[:, 4]

array([ 4,  9, 14, 19, 24])

In [9]:
'''
(0, 0) (5, 0)
(0, 5) (5, 5)
'''

'\n(0, 0) (5, 0)\n(0, 5) (5, 5)\n'

In [10]:
a = [(1, 2), (3, 4), (5, 6)]
a

[(1, 2), (3, 4), (5, 6)]

In [11]:
[(i[1], i[0]) for i in a]

[(2, 1), (4, 3), (6, 5)]

In [22]:
table

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
q = q_table(5)

array([[-0.25537584,  1.32603374, -0.69580764,  0.41998747],
       [-0.18542238,  1.78312162,  1.64293551, -2.74158931],
       [ 1.33782407,  1.13832075,  1.53652916, -0.14516832],
       [ 0.40151292,  0.14608515,  0.36644881, -0.14378416],
       [-0.30761975, -0.87662834,  0.6954408 ,  0.22768794],
       [ 0.59268782,  1.09617831, -0.54676084, -0.27051885],
       [ 1.43433815, -1.82701205,  1.38388126, -0.39179721],
       [-0.68726538,  0.8614944 , -1.29955851,  0.81460396],
       [ 1.71392612, -1.0465236 , -1.78245924, -0.81633416],
       [-0.57780646,  2.16325783, -0.85572286,  0.3611544 ],
       [ 1.24413767, -0.04728427, -0.0843212 ,  0.23837528],
       [ 0.11748068,  0.0861941 ,  1.39774974, -0.10240357],
       [-1.4448091 ,  0.26664515, -0.06398956,  0.48555186],
       [-0.12549259,  0.07745537,  1.20658068,  1.25823342],
       [ 1.5793871 , -0.49304194, -0.08382869, -0.28435015],
       [-0.44102026,  1.78910791, -0.52155494, -0.99962168],
       [ 0.10996023, -1.

In [37]:
table

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
pos = np.where(table == 7)
# pos = (pos[0], pos[1])
# pos


In [55]:
pos[0].item(), pos[1].item()

(1, 2)